services:
  schedule_ai_api_gateway:
    container_name: ${API_GATEWAY_HOST}
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    env_file: ".env"
    depends_on:
      schedule_ai_db:
        condition: service_healthy
      schedule_ai_db_manager:
        condition: service_started
      schedule_ai_openai:
        condition: service_started
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/schedule_ai.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  schedule_ai_db:
    container_name: ${DB_HOST}
    volumes:
      - schedule_ai_db_vol:/var/lib/mysql
    env_file: ".env"
    image: schedule_ai_db:latest
    build: ./db
  schedule_ai_db_manager:
    container_name: ${DB_MANAGER_HOST}
    env_file: ".env"
    depends_on:
      schedule_ai_db:
        condition: service_healthy
    image: schedule_ai_db_manager:latest
    build: ./db_manager
  schedule_ai_frontend:
    container_name: schedule_ai_frontend
    env_file: ".env"
    depends_on:
      schedule_ai_api_gateway:
        condition: service_started
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    image: schedule_ai_frontend:latest
    build: ./frontend
  schedule_ai_openai:
    container_name: ${OPENAI_HOST}
    env_file: ".env"
    image: schedule_ai_openai:latest
    build: ./openai
  
volumes:
  schedule_ai_db_vol:
    name: schedule_ai_db_vol